version: "3"
services:
  #auth
  auth_db:
    container_name: auth_db
    image: postgres
    volumes:
      - ./auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6377:6379"
  auth_server:
    build: ../auth/
    ports:
      - "8005:8009"
    
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      DB_HOST: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_PORT: 5432
      NODE_ENV: docker
      SECRET: secret
  auth_migration:
    build:
      context: ../auth/
      dockerfile: Dockerfile.migration
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      DB_HOST: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_PORT: 5432
      NODE_ENV: migration
  #backend
  app_db:
    container_name: app_db
    image: postgres
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5434:5432"
  app_server:
    build: ../backend/
    ports:
      - "8002:8001"
    volumes:
      - ../backend:/app
    depends_on:
      app_db:
        condition: service_healthy
    environment:
      DB_HOST: app_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app_db
      DB_PORT: 5432
      NODE_ENV: docker
      SECRET: secret
      AUTH_URL: http://auth_server:8009
      AUTH_PORT: 8009
  app_migration:
    build:
      context: ../backend/
      dockerfile: Dockerfile.migration
    depends_on:
      app_db:
        condition: service_healthy
    environment:
      DB_HOST: app_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app_db
      DB_PORT: 5432
      NODE_ENV: migration
      AUTH_URL: http://auth_server:8009
      AUTH_PORT: 8009